### ISSUE TITLE
Is "Experimental Breaks" an actual genre...

### ISSUE THREAD

**Issue by cartert54** [MCatalog/Genres#13]
Title

**Comment by Clbsfn** [comment]
I don't believe that it is. U/Navith's genre sheet doesn't have it, and on top of that googling "experimental breaks" brings up very little information that would indicate there is a genre called that out there.

And since Sweat by Karma Fields is the only release labeled "experimental breaks" on the mcatalog, it won't be a big deal at all just to change Sweat's genre to something on Navith's genre sheet, which contains 12 sugenres of Breaks.

**Comment by DylanMorrissey** [comment]
Navith's sheet can put "experimental" in front of any genre when they see fit and don't list it on the genres tab.

**Comment by Clbsfn** [comment]
Ohhh, i see. Yes, then perhaps we should do the same for Sweat.

**Comment by cartert54** [comment]
"Breaks" for now?

**Comment by Clbsfn** [comment]
I suppose just "Breaks" would be fine.
